### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/driving-game#1]
# Motivation

Users should be able to clearly see where their controlled car is located on the screen.

# Tasks

- [x] Create HTML, CSS, and JS files to contain the game
- [x] Create a Car class to create instances of car objects with previously used methods and properties
- [x] Use the Car class to instantiate a car object containing the user's car
- [x] Add and style a div in the HTML file to represent the car
- [x] Add an image property to the div to show a car sprite
- [x] Added a landing div to represent the area in which the car can drive
- [x] Position the car toward the left side of the screen facing the center
