### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/driving-game#2]
# Motivation

Before driving their car around the screen, users must be able to start their car.

# Tasks

- [x] Create a class Car in JavaScript with methods for controlling the car and properties for direction, speed, and location
- [x] Create a static method for starting car objects
- [x] Refactor car location system to conform to standard viewport coordinate system
- [x] Refactor HTML elements to utilize svg elements and relevant coordinate system
- [x] Render the car on the screen based on the location property of the car instance
- [x] Add an event listener that allows the player to start the car by pressing a certain key
- [x] Make the car move forward when started by rendering the screen every 16 milliseconds (60fps) while the location of the car is being updated
