### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/driving-game#3]
# Motivation

In addition to making the car move, users should be able to stop their car.

# Tasks

- [x] Refactor start static method into instance method
- [x] Add playerStatus to the game object to keep track of whether the player's car is started and save the timer id to stop the player's car
- [x] Add to the start method to clear the setInterval if the car is already started
- [x] Reset the playerStatus after the car has been stopped
