### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/driving-game#4]
# Motivation

Users should be able to change direction rather than drive in a straight line.

# Tasks

- [x] Add to the current event listener on the body to listen for the 'WASD' keys
- [x] Turn the car according to one of the pressed WASD keys
- [x] Add a conditional to prevent the car from being turned while stopped
