### ISSUE TITLE
User can accelerate and decelerate using the arrow keys.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/driving-game#9]
# Motivation

Users should be able to control the speed of their car, using the up and down arrow keys to accelerate and decelerate respectively.

# Tasks

- [x] Create a decelerate method on the Car class
- [x] Add to the body object event listener to detect keypresses of the up and down arrow keys
- [x] Call the Car.accelerate and Car.decelerate depending on the keypress
- [x] Set a minimum speed to prevent the speed from being lowered to 0
- [x] Set a maximum speed to prevent the car from being raised above a certain point
